## Load the Cleaned Dataset

In [1]:
import pandas as pd
df = pd.read_csv(
    "../data/processed/cleaned_demand_timeseries.csv",
    parse_dates = [0],
    index_col = 0
)

df.head()

C:\Users\ariel\AppData\Local\Temp\ipykernel_35896\3539524339.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(
C:\Users\ariel\AppData\Local\Temp\ipykernel_35896\3539524339.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(

   demand  demand_diff
1   20167        249.0
2   20328        161.0
3   19460       -868.0
4   18654       -806.0
5   18248       -406.0

## Creat Lag features

In [2]:
# Previous half hour
df["lag_1"] = df["demand"].shift(1)

# Same time previous day
df["lag_48"] = df["demand"].shift(48)

df[["demand", "lag_1", "lag_48"]].head(60)

    demand    lag_1   lag_48
1    20167      NaN      NaN
2    20328  20167.0      NaN
3    19460  20328.0      NaN
4    18654  19460.0      NaN
5    18248  18654.0      NaN
6    17855  18248.0      NaN
7    17367  17855.0      NaN
8    16774  17367.0      NaN
9    16489  16774.0      NaN
10   16289  16489.0      NaN
11   16498  16289.0      NaN
12   17411  16498.0      NaN
13   17485  17411.0      NaN
14   18095  17485.0      NaN
15   18171  18095.0      NaN
16   18688  18171.0      NaN
17   19399  18688.0      NaN
18   20754  19399.0      NaN
19   21697  20754.0      NaN
20   23023  21697.0      NaN
21   23550  23023.0      NaN
22   25023  23550.0      NaN
23   25618  25023.0      NaN
24   26600  25618.0      NaN
25   27073  26600.0      NaN
26   27517  27073.0      NaN
27   27419  27517.0      NaN
28   27504  27419.0      NaN
29   27807  27504.0      NaN
30   28104  27807.0      NaN
31   28258  28104.0      NaN
32   29332  28258.0      NaN
33   30573  29332.0      NaN
34   30977  30573.0      NaN
35   31045  30977.0      NaN
36   30715  31045.0      NaN
37   30142  30715.0      NaN
38   29570  30142.0      NaN
39   28965  29570.0      NaN
40   28445  28965.0      NaN
41   27382  28445.0      NaN
42   26484  27382.0      NaN
43   25340  26484.0      NaN
44   24526  25340.0      NaN
45   23266  24526.0      NaN
46   22276  23266.0      NaN
47   21513  22276.0      NaN
48   21449  21513.0      NaN
49   22173  21449.0  20167.0
50   21806  22173.0  20328.0
51   21180  21806.0  19460.0
52   20877  21180.0  18654.0
53   20476  20877.0  18248.0
54   20043  20476.0  17855.0
55   19939  20043.0  17367.0
56   19995  19939.0  16774.0
57   19935  19995.0  16489.0
58   20405  19935.0  16289.0
59   20897  20405.0  16498.0
60   22627  20897.0  17411.0

## Create Rolling Statistics

In [3]:
# Rolling mean (daily window)
df["rolling_mean_48"] = df["demand"].rolling(window=48).mean()

df[["demand", "rolling_mean_48"]].head(100)

     demand  rolling_mean_48
1     20167              NaN
2     20328              NaN
3     19460              NaN
4     18654              NaN
5     18248              NaN
..      ...              ...
96    25564     29080.666667
97    25674     29153.604167
98    25355     29227.541667
99    24800     29302.958333
100   24312     29374.520833

[100 rows x 2 columns]

## Extract Date & Time Components

In [4]:
# Critical features for XGBoost and LSTM
dt_idx = pd.DatetimeIndex(df.index)

df["hour"] = dt_idx.hour
df["day_of_week"] = dt_idx.dayofweek
df["month"] = dt_idx.month

df[["hour", "day_of_week", "month"]].head()

   hour  day_of_week  month
1     0            3      1
2     0            3      1
3     0            3      1
4     0            3      1
5     0            3      1

## Drop rows with NaNs (Created by Lags)

In [5]:
df_fe = df.dropna()

df_fe.isna().sum()

demand             0
demand_diff        0
lag_1              0
lag_48             0
rolling_mean_48    0
hour               0
day_of_week        0
month              0
dtype: int64

## Scale the clean feature matrix

In [8]:
from sklearn.preprocessing import MinMaxScaler

feature_cols = [
    "demand",
    "lag_1",
    "lag_48",
    "rolling_mean_48",
    "hour",
    "day_of_week",
    "month"
]

# Time-aware split (80/20)
split_index = int(len(df_fe) * 0.8)
train_fe = df_fe.iloc[:split_index]
test_fe = df_fe.iloc[split_index:]

# Fit scaler ONLY on training data
scaler = MinMaxScaler()
train_scaled = train_fe.copy()
test_scaled = test_fe.copy()

train_scaled[feature_cols] = scaler.fit_transform(train_fe[feature_cols])
test_scaled[feature_cols] = scaler.transform(test_fe[feature_cols])

## Save Feature-Engineered Dataset

In [9]:
# Save unscaled features (for tree models / ARIMA-style ML)
df_fe.to_csv("../data/processed/feature_engineered_unscaled.csv")

# Save scaled features (for LSTM / neural networks)
train_scaled.to_csv("../data/processed/feature_engineered_train_scaled.csv")
test_scaled.to_csv("../data/processed/feature_engineered_test_scaled.csv")

df_fe.head()

,demand,demand_diff,lag_1,lag_48,rolling_mean_48,hour,day_of_week,month
49,22173,724.0,21449.0,20167.0,23569.395833,0,3,1
50,21806,-367.0,22173.0,20328.0,23600.187500,0,3,1
51,21180,-626.0,21806.0,19460.0,23636.020833,0,3,1
52,20877,-303.0,21180.0,18654.0,23682.333333,0,3,1
53,20476,-401.0,20877.0,18248.0,23728.750000,0,3,1